{ hyprland, pkgs, lib, ...}: {

  imports = [
    hyprland.homeManagerModules.default
    ./programs
    # ./scripts
    # ./themes
  ];

  home = {
    username = "nemi";
    homeDirectory = lib.mkForce "/home/nemi/";
    stateVersion = "24.11";
    sessionVariables = {
      INPUT_METHOD = "fcitx5";
      GTK_IM_MODULE = "fcitx5";
      QT_IM_MODULE = "fcitx5";
      XMODIFIERS = "@im=fcitx5";
      GTK_THEME = "TokyoNight-Dark-B-MB";
      ICON_THEME = "TokyoNight";
    };
  };

  nixpkgs.config.allowUnfree = true;

  home.packages = (with pkgs; [

    kitty
    cool-retro-term # Literally what it says. Holy shit, I kinda really like this.

    qutebrowser # Keyboard-focused browser with minimal GUI
    brave # Need to find alternative to brave
    tor-browser # Anonymizing overlay network
    firefox
    # ladybird # Should try to get into using
    # zen # Experimental browser
    bitwarden-cli # Password manager
    bitwarden-desktop
    bitwarden-menu # Dmenu / rofi frontend for managing bitwarden vaults. Uses the Bitwarden-cli to interact with bitwarden database
    
    dunst
    fuzzel # wofi / rofi alternative for wayland. Seems much nicer

    anki
    obsidian
    mupdf # Lightweight PDF, XPS, and E-book viewer and toolkit. Contains mutool
    krita
    gimp
    discord
    discordo # Lightweight, feature-rich Discord terminal client
    # nautilus # Default GNOME file manager
    # sushi # Quick previewer for Nautilus
    #
    # When using nemo, only use one of these following "nemo" packages. Otherwise there will be an error as both packages collide
    ranger # Terminal file manager. VIM inspired
    # lf # ranger inspired terminal file manager. Minimalist and faster. Also way too hard to configure
    # ueberzugpp # Draws images on terminals using X11/Wayland child windows, sixels, kitty
    qbittorrent
    spotify
    steam
    retroarch
    godot3
    love

    mpv # free media player. Prefer over vlc
    celluloid # Basically just mpv
    # vlc # Media player
    qimgv # Image viewer

    # Utilities / command-line tools
    lazygit # simple terminal UI for Git Commands 
    gcc # GNU Compiler Collection. Need for a C compiler
    fzf # Fuzzy finder
    ripgrep # command-line search tool (recursive grep kinda)
    fd # find command
    evtest # Monitor and display events generated by input devices
    brightnessctl # Brightness controls
    lua # Lua
    luarocks # Lua official package manager
    curl # tool and library for transferring data with URLs
    wget # tool for retrieving files using HTTP, HTTPS, and FTP
    slurp
    grim
    wl-clipboard
    yt-dlp # video / media extractor
    ffmpeg # multimedia framework
    neofetch
    bc # Basic calculator
    tree #Command for quickly displaying contents of directory, including sub directories.
    # manix # Fast CLI documentation searcher for nix.
    gnumake # For the 'make' command. Useful for those makeFile files.
 

    #Miscellaneous
    kmonad
    notepadqq
    wireshark
    # ags # Aylur's GTK Shell
    clamav
    clamtk
    wireguard-tools
    wireguard-ui
  ]);
  gtk = {
    enable = true;
    theme = {
      name = "TokyoNight-Dark-B-MB";
      package = pkgs.tokyonight-gtk-theme;
    };
    iconTheme = {
      package = pkgs.adwaita-icon-theme;
      name = "Adwaita";
    };
  };

  # When using full GNOME system. This is good.
  # dconf.settings = {
  #   "org/gnome/desktop/interface" = {
  #     color-scheme = "prefer-dark";
  #   };
  #
  #   "org/gnome/shell/extensions/user-theme" = {
  #     name = "Tokyonight-Dark-B-LB";
  #   };
  # };
  programs = {
    home-manager = {
      enable = true;
    };
    zsh = {
      enable = true;
      oh-my-zsh = {
        enable = true;
        theme = "wedisagree";
        plugins = [ "git" "sudo" ];
      };
      shellAliases = {
        ll = "ls -lah";
        gs = "git status";
        battery = "cat /sys/class/power_supply/BAT0/capacity"; # Checking battery
        switchFlake = "sudo nixos-rebuild switch --flake .#nemi";
      };
    };
  };
}
